// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5J0BHwfIOz4CxsPqtU1IhEgsjgrrC20U',
    appId: '1:538906972899:web:484c49a5a2bdea6c78abd6',
    messagingSenderId: '538906972899',
    projectId: 'habitflow-c8119',
    authDomain: 'habitflow-c8119.firebaseapp.com',
    storageBucket: 'habitflow-c8119.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWwrw080j44NCUvC5RrLTZg8dtHHk2k0',
    appId: '1:538906972899:android:66503831c3564d4d78abd6',
    messagingSenderId: '538906972899',
    projectId: 'habitflow-c8119',
    storageBucket: 'habitflow-c8119.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5J0BHwfIOz4CxsPqtU1IhEgsjgrrC20U',
    appId: '1:538906972899:web:07eed8200e3dda9f78abd6',
    messagingSenderId: '538906972899',
    projectId: 'habitflow-c8119',
    authDomain: 'habitflow-c8119.firebaseapp.com',
    storageBucket: 'habitflow-c8119.firebasestorage.app',
  );
}
